name: Clean demo PR AWS resources

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      pr-number:
        description: 'PR number'
        required: true
        type: string
        #type: number
        #default: 000

jobs:
  clean-pr:
    strategy:
      matrix:
        include:
          - target: "dev"
            r53_zone: "Z00288701IWCJCEU7JLX1"
          - target: "uat"
            r53_zone: "Z02608583VKW5TMX3B5ED"
          - target: "prod"
            r53_zone: "Z0005272EGK5MRGCU1B9"
    runs-on: ubuntu-latest
    steps:
    - name: Clean AWS resources
      id: cleanup_routine
      run: |
        DEMO_NAME="pr-${{ inputs.pr-number }}"
        export DEMO_NAME && echo "DEMO_NAME=${DEMO_NAME}"