name: Weekly DEMO PR cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: 0 3 * * 6 # 03:00 hrs Sunday UTC ~> 22:00 hrs Sat NY

jobs:
  get-pr-records:
    runs-on: ubuntu-latest
    outputs:
      pr-list: ${{ steps.get_records.outputs.pr-list }}

    steps:
    - name: Get PR records
      id: get_records
      run: |
        list=()
        for i in 111 222 333; do \
        echo "Adding ${i} to list"; \
        list=(${list[@]} ${i}); done
        #refactored_list=($(printf "%s\n" "${list[@]}" | sort -u | tr '\n' ' '))
        #echo "pr-list=$(jq --compact-output --null-input '$ARGS.positional' --args -- ${refactored_list[@]})" | tee -a $GITHUB_OUTPUT
        echo "pr-list=[$(echo ${list[@]} |tr ' ' ',')]" | tee -a $GITHUB_OUTPUT

  clean-demo-pr:
    needs: get-pr-records
    strategy:
      matrix:
        pr-record: ${{ fromJSON(needs.get-pr-records.outputs.pr-list) }}
    uses: ./.github/workflows/clean-demo-pr.yml
    with:
      pr-number: ${{ matrix.pr-record }}
    secrets: inherit